Local fs
mozilla-iam/dino-park-fossil pull request #22
Opened 2020-08-05 08:18 UTC by jens1o

fixes #21

2020-08-05 13:10 UTC, jens1o commented
@fiji-flo While writing the implementation tests I came up with the question what the expected behavior should be when we try to delete a file which can't be found. What do you think? I personally tend to ignore this kind of `std::io::ErrorKind::NotFound` error, but one could also argue that some implementation in the future may depend on knowing whether a file was previously there and deleted by the `Saver` implementation or wasn't there in the first place.

2020-08-05 13:14 UTC, jens1o commented
As I don't have access to S3 (nor real experience with it), I cannot really say what that implementation does in that case (it is not clearly documented) and the filesystem is not version based as S3 is.

2020-08-06 06:38 UTC, fiji-flo requested changes
Looks great. Just a few minor things.

Also, please change the logging to start lowercase for consistency.

2020-08-06 06:38 UTC, fiji-flo commented on src/storage/saver/filesystem.rs
> +#[cfg(feature = "local-fs")]
We don't need this since it's only included in `mod.rs` if the feature is enabled.

2020-08-06 06:38 UTC, fiji-flo commented on src/storage/saver/filesystem.rs
> +#[cfg(feature = "local-fs")]
see above

2020-08-06 06:38 UTC, fiji-flo commented on src/storage/saver/filesystem.rs
> +                Err(err) => info!(
log as `warn!`

2020-08-06 13:04 UTC, fiji-flo approved these changes
:+1:

2020-08-06 13:41 UTC, jens1o commented
All commits are now signed, please merge at your discretion. :)

2020-08-06 13:55 UTC, merged