Fix png color metadata loss
mozilla-iam/dino-park-fossil pull request #23
Opened 2020-08-06 06:38 UTC by jens1o

Fixes https://github.com/mozilla-iam/dino-park-issues/issues/200

- [ ] Add tests

2020-08-06 13:54 UTC, fiji-flo requested changes
Only two things are the verbose info logging and a comment for the magic 33. Everything else is up to you.

Great work!

2020-08-06 13:54 UTC, fiji-flo commented on src/send/resize.rs
> +        info!(
lowercase and move to `debug!` maybe add a generic `info!("png metadata copied")` or something like that.

2020-08-06 13:54 UTC, fiji-flo commented on src/send/resize.rs
> +        const IMAGE_START_OFFSET_TO_ADD_DATA: usize = 33;
Maybe add a comment why 33 bytes offset.

2020-08-06 13:54 UTC, fiji-flo commented on src/send/resize.rs
> +        buf.truncate(IMAGE_START_OFFSET_TO_ADD_DATA);
[split_off](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.split_off) does this I think.

2020-08-06 13:54 UTC, fiji-flo commented on src/send/resize.rs
> +    fn maybe_extract_png_color_metadata(buf: &[u8]) -> Result<Vec<u8>, Error> {
Could also look like this:
```rust
    fn maybe_extract_png_color_metadata(buf: &[u8]) -> Result<Vec<u8>, Error> {
        let mut png_decoder = lodepng::Decoder::new();
        // required so the chunks are remembered (by default, it only remembers the mandatory chunks)
        png_decoder.remember_unknown_chunks(true);
        png_decoder.decode(&buf)?;

        let metadata_to_add = ["cHRM", "gAMA", "sRGB", "iCCP", "eXIf"]
            .iter()
            .filter_map(|chunk_to_copy| png_decoder.info_png().get(chunk_to_copy))
            .map(Avatars::metadata)
            .flatten()
            .collect();

        Ok(metadata_to_add)
    }

    fn metadata(data_chunk: lodepng::ChunkRef) -> Vec<u8> {
        // chunk_length = padding (2 bytes) chunk_len (4 bytes) + chunk type (4 bytes) + data_len + crc (8 bytes) = data_len + 18
        let mut metadata_to_add = Vec::with_capacity(data_chunk.len() + 18);

        // write two bytes of padding
        metadata_to_add.extend(&[0x00, 0x00]);
        metadata_to_add
            .write_u16::<byteorder::BE>(data_chunk.len() as u16)
            .unwrap();
        metadata_to_add.extend(&data_chunk.name());
        metadata_to_add.extend(data_chunk.data());

        metadata_to_add
            .write_u32::<byteorder::BE>(data_chunk.crc())
            .unwrap();

        metadata_to_add
    }
```

And moving the `info!` to the place we add the metadata. Optionally `debug!` log which chunks we copy in then `map`

2020-08-07 13:13 UTC, jens1o commented
@fiji-flo I just forgot to remind you about the S3 dump of the raw images regarding the post-processing and generation of new downsized images. Could you prepare that for me, please?

2020-08-10 06:49 UTC, fiji-flo approved these changes
Nice work.

2020-08-10 06:49 UTC, merged